import time
import logging

logger = logging.getLogger(__name__)

class ExecutorAgent:
    def __init__(self):
        self.metrics = {"actions_executed": 0, "failed_actions": 0}

    def execute_remediation(self, workflow_data):
        """Execute the remediation plan generated by the PlannerAgent."""
        incident_id = workflow_data.get("incident_id")
        logger.info(f"[ExecutorAgent] Starting execution for incident {incident_id}")
        
        remediation_plan = workflow_data.get("remediation_plan", {})
        actions = remediation_plan.get("actions", [])
        
        if not actions:
            logger.warning(f"[ExecutorAgent] No actions found in remediation plan for {incident_id}")
            return True
            
        incident_ip = workflow_data.get("data", {}).get("ip", "0.0.0.0")
        execution_results = []
        
        for index, action in enumerate(actions):
            logger.info(f"[ExecutorAgent] Executing action {index + 1}/{len(actions)}: {action.get('action')} on {action.get('target')}")
            result = self._simulate_execution(action, incident_ip)
            execution_results.append(result)
            
            if result["status"] == "SUCCESS":
                self.metrics["actions_executed"] += 1
            else:
                self.metrics["failed_actions"] += 1
                logger.error(f"[ExecutorAgent] Action failed: {result['message']}")
                
        workflow_data["execution_results"] = execution_results
        
        # Simulate overall processing
        time.sleep(1)
        logger.info(f"[ExecutorAgent] Execution complete for {incident_id}")
        
        return True

    def _simulate_execution(self, action, ip):
        """Simulate running system commands based on the action type."""
        action_name = action.get("action", "")
        target = action.get("target", "")
        
        result = {
            "action": action_name,
            "target": target,
            "timestamp": time.time(),
            "status": "SUCCESS",
            "simulated_command": "",
            "message": "Action completed successfully"
        }
        
        if action_name == "Add IP to Perimeter Blocklist":
            result["simulated_command"] = f'netsh advfirewall firewall add rule name="Block {ip}" dir=in action=block remoteip={ip}'
            result["message"] = f"IP {ip} successfully blocked at the perimeter firewall."
            
        elif action_name == "Isolate Asset from Network":
            result["simulated_command"] = 'Disable-NetAdapter -Name "*" -Confirm:$false'
            result["message"] = "Host network adapters disabled. System isolated."
            
        elif action_name == "Force Password Reset":
            result["simulated_command"] = 'Reset-ADServiceAccountPassword -Identity "AffectedUsers" -Force'
            result["message"] = "Password reset flags triggered for affected users in Active Directory."
            
        elif action_name == "Revoke Active Sessions":
            result["simulated_command"] = 'Revoke-AzureADUserAllRefreshToken -ObjectId "AffectedUsers"'
            result["message"] = "All active authentication sessions revoked."
            
        elif action_name == "Deploy Virtual Patch / Block Signature":
            result["simulated_command"] = 'Update-WAFPolicy -PolicyId "CoreProtect" -AddSignature "CVE-XXXX-XXXX"'
            result["message"] = "WAF policy updated with blocking signature."
            
        elif action_name == "Increase Monitoring and Logging":
            result["simulated_command"] = 'Set-EventLog -LogName Security -RetentionDays 90'
            result["message"] = "Diagnostic logging increased to verbose mode for affected systems."
            
        else:
            result["simulated_command"] = f'Invoke-CustomRemediation -Target "{target}"'
            result["message"] = f"Custom remediation script executed against {target}."
            
        # Simulate command execution time
        time.sleep(0.5)
        
        return result
