/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b4c5ff",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#004e5c",
        "on-primary-fixed": "#00174b",
        "on-tertiary-container": "#bdffdb",
        "outline": "#737686",
        "on-error": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "surface": "#f7f9fb",
        "primary-container": "#2563eb",
        "outline-variant": "#c3c6d7",
        "on-tertiary-fixed-variant": "#005236",
        "background": "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#b4c5ff",
        "surface-container-highest": "#e0e3e5",
        "surface-tint": "#0053db",
        "surface-bright": "#f7f9fb",
        "secondary-fixed": "#acedff",
        "primary": "#004ac6",
        "tertiary-container": "#007d55",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-container": "#006172",
        "tertiary": "#006242",
        "surface-container": "#eceef0",
        "on-tertiary": "#ffffff",
        "secondary-container": "#57dffe",
        "error-container": "#ffdad6",
        "on-background": "#191c1e",
        "on-primary-container": "#eeefff",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed": "#6ffbbe",
        "secondary": "#00687a",
        "on-surface-variant": "#434655",
        "tertiary-fixed-dim": "#4edea3",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed": "#001f26",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-dim": "#d8dadc",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-tertiary-fixed": "#002113",
        "on-surface": "#191c1e",
        "surface-container-low": "#f2f4f6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "stack-sm": "8px",
        "margin-desktop": "32px",
        "gutter": "24px",
        "unit": "4px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "stack-md": "16px"
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "mono-label": ["JetBrains Mono"],
        "headline-sm": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "mono-label": ["13px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
